# Generated by Django 4.2 on 2024-09-01 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blog_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='topic',
            field=models.CharField(choices=[('python', 'Python'), ('css', 'CSS'), ('html', 'HTML'), ('scss', 'SCSS'), ('django', 'Django'), ('javascript', 'Javascript'), ('angular', 'Angular'), ('docker', 'Docker'), ('kubernetes', 'Kubernetes'), ('git', 'Git'), ('bootstrap', 'Bootstrap'), ('tailwind', 'Tailwind')], max_length=100),
        ),
    ]
