# Generated by Django 4.2 on 2024-09-01 07:00

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('client', models.CharField(max_length=100)),
                ('year', models.DateField()),
                ('work_description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('technologies_used', multiselectfield.db.fields.MultiSelectField(choices=[('python', 'Python'), ('css', 'CSS'), ('html', 'HTML'), ('scss', 'SCSS'), ('django', 'Django'), ('javascript', 'Javascript'), ('angular', 'Angular'), ('docker', 'Docker'), ('kubernetes', 'Kubernetes'), ('git', 'Git'), ('bootstrap', 'Bootstrap'), ('tailwind', 'Tailwind')], max_length=87)),
                ('work_details', ckeditor_uploader.fields.RichTextUploadingField()),
                ('photos', models.FileField(upload_to='photos/')),
                ('credits', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Work',
                'verbose_name_plural': 'Works',
            },
        ),
    ]
